id: 3ebfb315-d0a6-4b27-9f89-b16a9a1ada5f
name: java
description: |
  ## Complete Quickstart for Monitoring Java
  ### Why Monitoring Java is So Important
  Java is a compiled language, which means it has the potential to be fast. However, there are a a lot of Java-specific quirks that make the average program slow such as  high default memory usage and lags in the startup time of the JVM. 

  When using Java as a website backend, slowdowns in performance can lead to long page load times, causing users to prematurely leave your site. In order to get the most performance out of your Java applications, it’s important to continuously monitor them with tools such as  New Relic agent for Java. 

  ### New Relic Java Pack Features
  - Alerts for various metrics including high cpu utilization and transaction errors
  - Dashboards showing average CPU utilization, memory heap used, garbage collection CPU time, top 5 slowest transactions, and more.


  ### New Relic - The Perfect Java Observability Tool
  Proactive Java monitoring yields real, quantifiable reductions in website latency and leads users to be more likely to stay on a given site. Our Javaagent monitors app servers, databases, and message queuing systems, giving insight into all the key components which allow a web application to run. Custom instrumentation is also available for the add-on Java frameworks and libraries which may be used. 

  Regardless of what’s being monitored, the agent reports metric time-slice and event data, giving insight at regularly scheduled intervals. It also provides observability at the level of the JVM, giving measurements of thread pools, HTTP sessions, and transactions. You can even trace request flows through distributed systems, allowing you to pinpoint points of failure and prevent downtime before it occurs. All metrics and interfaces are unified via a helpful java dashboard which provides a visual display of an application’s performance.
summary: |
  Monitor Java with New Relic's Java agent
icon: icon.svg
logo: logo.svg
level: Community
authors:
  - New Relic
  - Emil Hammarstrand
title: Java
documentation:
  - name: Java installation docs
    description: |
      Popular object-oriented programming language with widespread platform and
      operating system support.
    url: >-
      https://docs.newrelic.com/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent
keywords:
  - apm
  - java
  - language agent

installPlans:
  - setup-java-agent
