id: 3ebfb315-d0a6-4b27-9f89-b16a9a1ada5f
name: java
description: |
  # What is Java?

  Popular object-oriented programming language with widespread platform and operating system support.


  ## Get started!

  Leverage community expertise and instantly get value out of your telemetry data. This quickstart automatically instruments Java with the New Relic Java agent, and allows you to instantly monitor your Java application with out-of-the-box dashboards and alerts. 


  ## More info

  Check out the [documentation](https://docs.newrelic.com/docs/agents/java-agent/getting-started/introduction-new-relic-java/) to learn more about New Relic monitoring for Java.
summary: |
  The New Relic Java quickstart provides insight into application performance, improves uptime, and reduces latency. Monitoring is reported using metric time-slice and event data, and all results are displayed in easy-to-use, visual dashboards.
icon: icon.svg
logo: logo.svg
level: New Relic
authors:
  - New Relic
  - Emil Hammarstrand
title: Java
documentation:
  - name: Java installation docs
    description: |
      Popular object-oriented programming language with widespread platform and
      operating system support.
    url: >-
      https://docs.newrelic.com/docs/agents/java-agent/getting-started/compatibility-requirements-java-agent
keywords:
  - apm
  - java
  - language agent

installPlans:
  - setup-java-agent
